"""Initial schema

Revision ID: 2ed31126b1f4
Revises: 
Create Date: 2026-09-26 12:13:11.173973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.models


# revision identifiers, used by Alembic.
revision: str = '2ed31126b1f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.database.models.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('api_credentials',
    sa.Column('id', app.database.models.GUID(length=36), nullable=False),
    sa.Column('user_id', app.database.models.GUID(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('key_name', sa.String(length=100), nullable=False),
    sa.Column('encrypted_secret', sa.LargeBinary(), nullable=False),
    sa.Column('key_hint', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('test_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.create_index('idx_api_credentials_provider', ['user_id', 'provider'], unique=False)
        batch_op.create_index('idx_api_credentials_user', ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', app.database.models.GUID(length=36), nullable=False),
    sa.Column('user_id', app.database.models.GUID(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', app.database.models.GUID(length=36), nullable=True),
    sa.Column('details', app.database.models.JSONType(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_action', ['action', 'timestamp'], unique=False)
        batch_op.create_index('idx_audit_logs_user', ['user_id'], unique=False)

    op.create_table('auth_accounts',
    sa.Column('id', app.database.models.GUID(length=36), nullable=False),
    sa.Column('user_id', app.database.models.GUID(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('provider_data', app.database.models.JSONType(), nullable=True),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_provider_user_id')
    )
    with op.batch_alter_table('auth_accounts', schema=None) as batch_op:
        batch_op.create_index('idx_auth_accounts_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_accounts', schema=None) as batch_op:
        batch_op.drop_index('idx_auth_accounts_user')

    op.drop_table('auth_accounts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_logs_user')
        batch_op.drop_index('idx_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_credentials', schema=None) as batch_op:
        batch_op.drop_index('idx_api_credentials_user')
        batch_op.drop_index('idx_api_credentials_provider')

    op.drop_table('api_credentials')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
