// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/LuxuryWatchReserveDashboard-bu_8ck/App.tsx": () => import("../components/mockups/templates/LuxuryWatchReserveDashboard-bu_8ck/App.tsx"),
  "./components/mockups/templates/SwissLearningApp-GuYbpB/App.tsx": () => import("../components/mockups/templates/SwissLearningApp-GuYbpB/App.tsx"),
  "./components/mockups/templates/SwissLearningApp-Lj42IS/App.tsx": () => import("../components/mockups/templates/SwissLearningApp-Lj42IS/App.tsx"),
  "./components/mockups/templates/SwissLearningApp-hHgNSY/App.tsx": () => import("../components/mockups/templates/SwissLearningApp-hHgNSY/App.tsx"),
  "./components/mockups/templates/SwissLearningApp-k3fcy5/App.tsx": () => import("../components/mockups/templates/SwissLearningApp-k3fcy5/App.tsx")
};
